# Generated by Django 5.1.6 on 2025-03-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='type',
            field=models.CharField(blank=True, choices=[('ECD', 'Early Childhood Development'), ('Primary', 'Primary'), ('Secondary', 'Secondary'), ('Other', 'Other')], max_length=200, null=True),
        ),
    ]
