# Generated by Django 5.1.6 on 2025-03-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0002_school_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='type',
            field=models.CharField(blank=True, choices=[('ECDC', 'Early Childhood Development'), ('Primary School', 'Primary School'), ('Secondary School', 'Secondary School'), ('Other', 'Other')], max_length=200, null=True),
        ),
    ]
