# Generated by Django 5.1.6 on 2025-10-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('STAFF', 'Staff Member'), ('PROJECT MANAGER', 'Project Manager'), ('MENTOR', 'Mentor'), ('VIEWER', 'Viewer'), ('FUNDER', 'Funder'), ('YOUTH', 'Youth')], default='VIEWER', max_length=20),
        ),
    ]
