# Generated by Django 5.1.6 on 2025-05-14 14:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AirtableSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(max_length=50, verbose_name='Sync Type')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('records_processed', models.IntegerField(default=0, verbose_name='Records Processed')),
                ('records_created', models.IntegerField(default=0, verbose_name='Records Created')),
                ('records_updated', models.IntegerField(default=0, verbose_name='Records Updated')),
                ('records_skipped', models.IntegerField(default=0, verbose_name='Records Skipped')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('success', models.BooleanField(default=False, verbose_name='Success')),
            ],
            options={
                'verbose_name': 'Airtable Sync Log',
                'verbose_name_plural': 'Airtable Sync Logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airtable_id', models.CharField(blank=True, help_text='Airtable record ID', max_length=100, null=True, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(blank=True, choices=[('ECDC', 'Early Childhood Development'), ('Primary School', 'Primary School'), ('Secondary School', 'Secondary School'), ('Other', 'Other')], max_length=200, null=True)),
                ('site_type', models.CharField(blank=True, help_text='Site type from Airtable', max_length=100, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mentor',
                'verbose_name_plural': 'Mentors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MentorVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(default=django.utils.timezone.now)),
                ('letter_trackers_correct', models.BooleanField(default=False, verbose_name="Are LC's using their Letter Trackers correctly?")),
                ('reading_trackers_correct', models.BooleanField(default=False, verbose_name="Are LC's using their Reading Trackers correctly?")),
                ('sessions_correct', models.BooleanField(default=False, verbose_name="Are TA's using their Session Trackers correctly?")),
                ('admin_correct', models.BooleanField(default=False, verbose_name="Are TA's completing their admin correctly?")),
                ('quality_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=5, verbose_name='Quality of Sessions Observed')),
                ('supplies_needed', models.TextField(blank=True, null=True, verbose_name='Any Supplies Needed')),
                ('commentary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='api.school')),
            ],
            options={
                'verbose_name': 'Mentor Visit',
                'verbose_name_plural': 'Mentor Visits',
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airtable_id', models.CharField(blank=True, help_text='Airtable record ID', max_length=100, null=True, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('mcode', models.CharField(blank=True, help_text='Unique code for the child', max_length=50, null=True)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('on_programme', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.school')),
            ],
            options={
                'verbose_name': 'Child',
                'verbose_name_plural': 'Children',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Youth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airtable_id', models.CharField(blank=True, help_text='Airtable record ID', max_length=100, null=True, unique=True)),
                ('employee_id', models.IntegerField(unique=True)),
                ('first_names', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('race', models.CharField(blank=True, choices=[('Black African', 'Black African'), ('Coloured', 'Coloured'), ('White', 'White'), ('Indian/Asian', 'Indian/Asian'), ('Other', 'Other')], max_length=20, null=True)),
                ('id_type', models.CharField(blank=True, choices=[('RSA ID', 'RSA ID'), ('Foreign ID', 'Foreign ID'), ('Passport', 'Passport')], max_length=20, null=True)),
                ('rsa_id_number', models.CharField(blank=True, max_length=13, null=True)),
                ('foreign_id_number', models.CharField(blank=True, max_length=30, null=True)),
                ('cell_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('emergency_number', models.CharField(blank=True, max_length=20, null=True)),
                ('street_number', models.CharField(blank=True, max_length=20, null=True)),
                ('street_address', models.CharField(blank=True, max_length=255, null=True)),
                ('suburb_township', models.CharField(blank=True, max_length=255, null=True)),
                ('city_or_town', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('employment_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('reason_for_leaving', models.CharField(blank=True, max_length=255, null=True)),
                ('income_tax_number', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_type', models.CharField(blank=True, choices=[('Savings', 'Savings'), ('Current', 'Current'), ('Cheque', 'Cheque')], max_length=20, null=True)),
                ('branch_code', models.CharField(blank=True, max_length=20, null=True)),
                ('account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentored_youth', to='api.mentor')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='youth', to='api.school')),
            ],
            options={
                'verbose_name': 'Youth',
                'verbose_name_plural': 'Youth',
                'ordering': ['last_name', 'first_names'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airtable_id', models.CharField(help_text='Airtable record ID', max_length=100, unique=True)),
                ('session_id', models.IntegerField(unique=True, verbose_name='Session ID')),
                ('total_weekly_sessions', models.IntegerField(default=0, verbose_name='Total Weekly Sessions')),
                ('submitted_for_week', models.IntegerField(default=0, verbose_name='Submitted for Week')),
                ('week', models.CharField(max_length=50)),
                ('month', models.CharField(max_length=50)),
                ('month_year', models.CharField(max_length=50, verbose_name='Month and Year')),
                ('sessions_met_minimum', models.CharField(max_length=10, verbose_name='Met Minimum')),
                ('capture_date', models.DateField(verbose_name='Capture Date')),
                ('created_in_airtable', models.DateTimeField(verbose_name='Created in Airtable')),
                ('created_in_system', models.DateTimeField(auto_now_add=True, verbose_name='Created in System')),
                ('updated_in_system', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.child')),
                ('mentor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='api.mentor')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.school')),
                ('youth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.youth')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'ordering': ['-capture_date'],
            },
        ),
    ]
