# Generated by Django 5.1.6 on 2025-05-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_youth_account_number_alter_youth_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='youth',
            name='income_tax_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
