# Generated by Django 5.1.6 on 2025-05-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_youth_race_field_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youth',
            name='race',
            field=models.CharField(blank=True, choices=[('Black African', 'Black African'), ('Coloured', 'Coloured'), ('White', 'White'), ('Indian/Asian', 'Indian/Asian'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
