# Generated by Django 5.1.6 on 2025-05-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_youth_race'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentor',
            options={'ordering': ['name'], 'verbose_name': 'Mentor Visit', 'verbose_name_plural': 'Mentor Visits'},
        ),
        migrations.AddField(
            model_name='school',
            name='actively_working_in',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='principal',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='school_id',
            field=models.IntegerField(blank=True, help_text='School ID from CSV import', null=True),
        ),
    ]
