# Generated by Django 5.1.6 on 2025-05-27 18:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_mentor_options_school_actively_working_in_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YeboVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(default=django.utils.timezone.now)),
                ('paired_reading_took_place', models.BooleanField(default=False, verbose_name='Did paired reading take place?')),
                ('paired_reading_tracking_updated', models.BooleanField(default=False, verbose_name='Paired reading tracking up to date')),
                ('afternoon_session_quality', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=5, verbose_name='Afternoon session quality')),
                ('commentary', models.TextField(blank=True, null=True, verbose_name='Commentary')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yebo_visits', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yebo_visits', to='api.school')),
            ],
            options={
                'verbose_name': 'Yebo Visit',
                'verbose_name_plural': 'Yebo Visits',
                'ordering': ['-visit_date'],
            },
        ),
    ]
