# Generated by Django 5.1.6 on 2025-05-27 18:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_school_school_id_yebovisit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThousandStoriesVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(default=django.utils.timezone.now)),
                ('library_neat_and_tidy', models.BooleanField(default=False, verbose_name='Is the library neat and tidy?')),
                ('tracking_sheets_up_to_date', models.BooleanField(default=False, verbose_name='Are all tracking sheets up to date?')),
                ('book_boxes_and_borrowing', models.BooleanField(default=False, verbose_name='Is book boxes and book borrowing taking place?')),
                ('daily_target_met', models.BooleanField(default=False, verbose_name='Daily target of stories read is met?')),
                ('story_time_quality', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=5, verbose_name='Quality of Story time session')),
                ('other_comments', models.TextField(blank=True, null=True, verbose_name='Other comments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thousand_stories_visits', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thousand_stories_visits', to='api.school')),
            ],
            options={
                'verbose_name': '1000 Stories Visit',
                'verbose_name_plural': '1000 Stories Visits',
                'ordering': ['-visit_date'],
            },
        ),
    ]
