# Generated by Django 5.1.6 on 2025-08-13 13:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_mark_school_id_exists'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NumeracyVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(default=django.utils.timezone.now)),
                ('numeracy_tracker_correct', models.BooleanField(default=False, verbose_name='Using Numeracy Tracker Correctly')),
                ('teaching_counting', models.BooleanField(default=False, verbose_name='Teaching Counting')),
                ('teaching_number_concepts', models.BooleanField(default=False, verbose_name='Teaching Number Concepts')),
                ('teaching_patterns', models.BooleanField(default=False, verbose_name='Teaching Patterns')),
                ('teaching_addition_subtraction', models.BooleanField(default=False, verbose_name='Teaching Addition/Subtraction')),
                ('quality_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=5, verbose_name='Quality of Sessions Observed')),
                ('supplies_needed', models.TextField(blank=True, null=True, verbose_name='Any Supplies Needed')),
                ('commentary', models.TextField(blank=True, null=True, verbose_name='Commentary')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numeracy_visits', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numeracy_visits', to='api.school')),
            ],
            options={
                'verbose_name': 'Numeracy Visit',
                'verbose_name_plural': 'Numeracy Visits',
                'ordering': ['-visit_date'],
            },
        ),
    ]
