# Generated by Django 5.1.6 on 2025-10-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_numeracyvisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiteracySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.IntegerField(unique=True)),
                ('lc_full_name', models.CharField(blank=True, max_length=255)),
                ('child_full_name', models.CharField(blank=True, max_length=255)),
                ('school', models.CharField(blank=True, max_length=255)),
                ('grade', models.CharField(blank=True, max_length=50)),
                ('sessions_capture_date', models.DateField(blank=True, null=True)),
                ('total_weekly_sessions_received', models.IntegerField(default=0)),
                ('reading_level', models.CharField(blank=True, max_length=100)),
                ('letters_done', models.JSONField(blank=True, default=list)),
                ('mentor', models.CharField(blank=True, max_length=255)),
                ('site_type', models.CharField(blank=True, max_length=100)),
                ('on_the_programme', models.CharField(blank=True, max_length=50)),
                ('month', models.CharField(blank=True, max_length=50)),
                ('week', models.CharField(blank=True, max_length=50)),
                ('month_and_year', models.CharField(blank=True, max_length=50)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('sessions_met_minimum', models.CharField(blank=True, max_length=10)),
                ('duplicate_flag', models.CharField(blank=True, max_length=255)),
                ('employee_id', models.CharField(blank=True, max_length=50)),
                ('mcode', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
