# Generated by Django 5.1.6 on 2025-10-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_literacysession'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumeracySessionChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('nc_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('numeracy_site', models.CharField(blank=True, max_length=255, null=True)),
                ('child_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sessions_capture_date', models.DateField(blank=True, null=True)),
                ('children_in_group', models.IntegerField(blank=True, null=True)),
                ('created', models.CharField(blank=True, max_length=50, null=True)),
                ('current_count_level', models.CharField(blank=True, max_length=50, null=True)),
                ('baseline_count_level', models.JSONField(blank=True, default=list, null=True)),
                ('number_recognition', models.CharField(blank=True, max_length=50, null=True)),
                ('month', models.CharField(blank=True, max_length=50, null=True)),
                ('week', models.CharField(blank=True, max_length=50, null=True)),
                ('month_and_year', models.CharField(blank=True, max_length=50, null=True)),
                ('all_sites', models.JSONField(blank=True, default=list, null=True)),
                ('site_placement', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=255, null=True)),
                ('mentor', models.CharField(blank=True, max_length=255, null=True)),
                ('employment_status', models.CharField(blank=True, max_length=255, null=True)),
                ('duplicate_flag', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Numeracy Session (Child Level)',
                'verbose_name_plural': 'Numeracy Sessions (Child Level)',
                'indexes': [models.Index(fields=['session_id'], name='api_numerac_session_b06535_idx'), models.Index(fields=['nc_full_name'], name='api_numerac_nc_full_530a7f_idx'), models.Index(fields=['numeracy_site'], name='api_numerac_numerac_d6c8de_idx'), models.Index(fields=['child_name'], name='api_numerac_child_n_3e9f76_idx')],
            },
        ),
    ]
