# Generated by Django 5.1.6 on 2025-12-01 17:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_numeracysessionchild'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment2025',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airtable_id', models.CharField(help_text='Airtable record ID for syncing', max_length=100, unique=True)),
                ('mcode', models.CharField(blank=True, db_index=True, help_text='Unique student identifier', max_length=100, null=True)),
                ('surname', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('race', models.CharField(blank=True, choices=[('Black', 'Black'), ('Coloured', 'Coloured')], max_length=20, null=True)),
                ('language', models.CharField(blank=True, choices=[('IsiXhosa', 'IsiXhosa'), ('English', 'English')], max_length=20, null=True)),
                ('school', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('grade', models.CharField(blank=True, choices=[('PreR', 'PreR'), ('Grade R', 'Grade R'), ('Grade 1', 'Grade 1'), ('Grade 2', 'Grade 2'), ('Grade 3', 'Grade 3')], max_length=20, null=True)),
                ('class_name', models.CharField(blank=True, help_text='Class identifier (e.g., RA, RB, 1A)', max_length=20, null=True)),
                ('teacher', models.CharField(blank=True, max_length=100, null=True)),
                ('centre_type', models.CharField(blank=True, choices=[('Primary', 'Primary'), ('ECD', 'ECD'), ('Both', 'Both'), ('Wcd', 'Wcd')], max_length=20, null=True)),
                ('mentor', models.CharField(blank=True, max_length=100, null=True)),
                ('on_programme', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Awaiting', 'Awaiting'), ('Left', 'Left'), ('Absent', 'Absent')], max_length=20, null=True)),
                ('capturer', models.CharField(blank=True, help_text='Person who captured the data', max_length=100, null=True)),
                ('baseline_status', models.CharField(blank=True, choices=[('Present Baseline', 'Present Baseline'), ('Missing Baseline', 'Missing Baseline')], max_length=20, null=True)),
                ('midline_status', models.CharField(blank=True, choices=[('Midline Present', 'Midline Present'), ('Midline Missing', 'Midline Missing'), ('N/A', 'N/A')], max_length=20, null=True)),
                ('endline_status', models.CharField(blank=True, choices=[('Present Endline', 'Present Endline'), ('Missing Endline', 'Missing Endline')], max_length=20, null=True)),
                ('jan_letter_sounds', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('jan_story_comprehension', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('jan_listen_first_sound', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('jan_listen_words', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('jan_writing_letters', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('jan_read_words', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('jan_read_sentences', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('jan_read_story', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('jan_write_cvcs', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('jan_write_sentences', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('jan_write_story', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('jan_total', models.IntegerField(blank=True, help_text='Computed total of all January scores', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('june_letter_sounds', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('june_story_comprehension', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('june_listen_first_sound', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('june_listen_words', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('june_writing_letters', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('june_read_words', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('june_read_sentences', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('june_read_story', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('june_write_cvcs', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('june_write_sentences', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('june_write_story', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('june_total', models.IntegerField(blank=True, help_text='Computed total of all June scores', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('nov_letter_sounds', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('nov_story_comprehension', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('nov_listen_first_sound', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('nov_listen_words', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('nov_writing_letters', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('nov_read_words', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('nov_read_sentences', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('nov_read_story', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('nov_write_cvcs', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('nov_write_sentences', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('nov_write_story', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('nov_total', models.IntegerField(blank=True, help_text='Computed total of all November scores', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '2025 Assessment',
                'verbose_name_plural': '2025 Assessments',
                'db_table': 'assessment_2025',
                'indexes': [models.Index(fields=['mcode'], name='assessment__mcode_040085_idx'), models.Index(fields=['school'], name='assessment__school_1122e3_idx'), models.Index(fields=['grade'], name='assessment__grade_234824_idx'), models.Index(fields=['mentor'], name='assessment__mentor_abaad8_idx'), models.Index(fields=['on_programme'], name='assessment__on_prog_eabe41_idx')],
            },
        ),
    ]
