# Generated by Django 5.1.6 on 2025-12-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_add_assessment_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment2025',
            name='exclude',
            field=models.BooleanField(blank=True, help_text='Mark True to exclude this record from analysis', null=True),
        ),
        migrations.AddField(
            model_name='assessment2025',
            name='exclude_reason',
            field=models.TextField(blank=True, help_text='Reason for excluding this record', null=True),
        ),
    ]
