# Generated by Django 5.1.6 on 2026-01-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_add_exclude_fields_to_assessment_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorvisit',
            name='quality_rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True, verbose_name='Quality of Sessions Observed'),
        ),
        migrations.AlterField(
            model_name='numeracyvisit',
            name='quality_rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True, verbose_name='Quality of Sessions Observed'),
        ),
        migrations.AlterField(
            model_name='thousandstoriesvisit',
            name='story_time_quality',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True, verbose_name='Quality of Story time session'),
        ),
        migrations.AlterField(
            model_name='yebovisit',
            name='afternoon_session_quality',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True, verbose_name='Afternoon session quality'),
        ),
    ]
