# Generated by Django 5.1.6 on 2026-01-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_update_quality_ratings_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorvisit',
            name='visit_type',
            field=models.CharField(choices=[('observation', 'Observation'), ('meeting', 'Meeting'), ('delivery', 'Delivery'), ('other', 'Other')], default='observation', max_length=20, verbose_name='Type of Visit'),
        ),
        migrations.AlterField(
            model_name='mentorvisit',
            name='admin_correct',
            field=models.BooleanField(blank=True, null=True, verbose_name="Are TA's completing their admin correctly?"),
        ),
        migrations.AlterField(
            model_name='mentorvisit',
            name='letter_trackers_correct',
            field=models.BooleanField(blank=True, null=True, verbose_name="Are LC's using their Letter Trackers correctly?"),
        ),
        migrations.AlterField(
            model_name='mentorvisit',
            name='reading_trackers_correct',
            field=models.BooleanField(blank=True, null=True, verbose_name="Are LC's using their Reading Trackers correctly?"),
        ),
        migrations.AlterField(
            model_name='mentorvisit',
            name='sessions_correct',
            field=models.BooleanField(blank=True, null=True, verbose_name="Are TA's using their Session Trackers correctly?"),
        ),
    ]
