# Generated by Django 5.1.6 on 2026-01-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_mentorvisit_visit_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yebovisit',
            name='after_school_observation',
            field=models.TextField(blank=True, null=True, verbose_name='After-School Observation'),
        ),
        migrations.AddField(
            model_name='yebovisit',
            name='paired_reading_observation',
            field=models.TextField(blank=True, null=True, verbose_name='Paired Reading Observation'),
        ),
    ]
