# Generated by Django 5.1.6 on 2026-01-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_yebovisit_after_school_observation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='numeracyvisit',
            name='visit_type',
            field=models.CharField(choices=[('observation', 'Observation'), ('meeting', 'Meeting'), ('delivery', 'Delivery'), ('other', 'Other')], default='observation', max_length=20, verbose_name='Type of Visit'),
        ),
        migrations.AddField(
            model_name='thousandstoriesvisit',
            name='visit_type',
            field=models.CharField(choices=[('observation', 'Observation'), ('meeting', 'Meeting'), ('delivery', 'Delivery'), ('other', 'Other')], default='observation', max_length=20, verbose_name='Type of Visit'),
        ),
        migrations.AddField(
            model_name='yebovisit',
            name='visit_type',
            field=models.CharField(choices=[('observation', 'Observation'), ('meeting', 'Meeting'), ('delivery', 'Delivery'), ('other', 'Other')], default='observation', max_length=20, verbose_name='Type of Visit'),
        ),
        migrations.AlterField(
            model_name='numeracyvisit',
            name='numeracy_tracker_correct',
            field=models.BooleanField(blank=True, null=True, verbose_name='Using Numeracy Tracker Correctly'),
        ),
        migrations.AlterField(
            model_name='numeracyvisit',
            name='teaching_addition_subtraction',
            field=models.BooleanField(blank=True, null=True, verbose_name='Teaching Addition/Subtraction'),
        ),
        migrations.AlterField(
            model_name='numeracyvisit',
            name='teaching_counting',
            field=models.BooleanField(blank=True, null=True, verbose_name='Teaching Counting'),
        ),
        migrations.AlterField(
            model_name='numeracyvisit',
            name='teaching_number_concepts',
            field=models.BooleanField(blank=True, null=True, verbose_name='Teaching Number Concepts'),
        ),
        migrations.AlterField(
            model_name='numeracyvisit',
            name='teaching_patterns',
            field=models.BooleanField(blank=True, null=True, verbose_name='Teaching Patterns'),
        ),
        migrations.AlterField(
            model_name='thousandstoriesvisit',
            name='book_boxes_and_borrowing',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is book boxes and book borrowing taking place?'),
        ),
        migrations.AlterField(
            model_name='thousandstoriesvisit',
            name='daily_target_met',
            field=models.BooleanField(blank=True, null=True, verbose_name='Daily target of stories read is met?'),
        ),
        migrations.AlterField(
            model_name='thousandstoriesvisit',
            name='library_neat_and_tidy',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is the library neat and tidy?'),
        ),
        migrations.AlterField(
            model_name='thousandstoriesvisit',
            name='tracking_sheets_up_to_date',
            field=models.BooleanField(blank=True, null=True, verbose_name='Are all tracking sheets up to date?'),
        ),
        migrations.AlterField(
            model_name='yebovisit',
            name='paired_reading_took_place',
            field=models.BooleanField(blank=True, null=True, verbose_name='Did paired reading take place?'),
        ),
        migrations.AlterField(
            model_name='yebovisit',
            name='paired_reading_tracking_updated',
            field=models.BooleanField(blank=True, null=True, verbose_name='Paired reading tracking up to date'),
        ),
    ]
