# Generated by Django 5.1.6 on 2026-03-09 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_numeracyvisit_visit_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='numeracysessionchild',
            name='source_airtable_id',
            field=models.CharField(blank=True, db_index=True, help_text='Airtable record ID — used as upsert key so we never delete the whole table', max_length=100, null=True),
        ),
    ]
