# Generated by Django 5.1.6 on 2026-03-10 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_numeracysessionchild_source_airtable_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiteracySession2026',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_airtable_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('session_record', models.IntegerField(blank=True, help_text='Airtable auto-number', null=True)),
                ('session_uid', models.CharField(blank=True, db_index=True, help_text='Composite business key: SES-date-YTH-SCH-CH', max_length=200, null=True)),
                ('session_date', models.DateField(blank=True, null=True)),
                ('youth_uid', models.CharField(blank=True, db_index=True, help_text='e.g. YTH-1905', max_length=50, null=True)),
                ('school_uid', models.CharField(blank=True, db_index=True, help_text='e.g. SCH-00283', max_length=50, null=True)),
                ('child_uid_1', models.CharField(blank=True, help_text='e.g. CH-16023', max_length=50, null=True)),
                ('child_uid_2', models.CharField(blank=True, help_text='e.g. CH-16566', max_length=50, null=True)),
                ('child_names', models.CharField(blank=True, help_text='Semicolon-separated child names from Airtable', max_length=500, null=True)),
                ('sounds_covered', models.CharField(blank=True, help_text='Raw sounds covered text entered by LC', max_length=500, null=True)),
                ('sounds_covered_clean', models.CharField(blank=True, help_text='Normalised sounds (lowercased, punctuation removed)', max_length=500, null=True)),
                ('blending_level', models.CharField(blank=True, max_length=100, null=True)),
                ('duplicate_status', models.CharField(blank=True, help_text='e.g. Unique or Duplicate', max_length=50, null=True)),
                ('overall_session_status', models.CharField(blank=True, help_text='Clean or Needs fix', max_length=50, null=True)),
                ('capture_delay', models.IntegerField(blank=True, help_text='Days between session date and when it was captured', null=True)),
                ('capture_delay_flag', models.CharField(blank=True, max_length=100, null=True)),
                ('duplicate_fingerprint', models.CharField(blank=True, help_text='Composite string used for duplicate detection', max_length=500, null=True)),
                ('created_in_airtable', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'literacy_sessions_2026',
                'indexes': [models.Index(fields=['session_date'], name='literacy_se_session_58dd10_idx'), models.Index(fields=['youth_uid'], name='literacy_se_youth_u_dd1642_idx'), models.Index(fields=['school_uid'], name='literacy_se_school__9e6efd_idx')],
            },
        ),
    ]
