# Generated by Django 5.1.6 on 2026-03-10 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_literacysession2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumeracySession2026',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_airtable_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('session_record', models.IntegerField(blank=True, help_text='Airtable auto-number', null=True)),
                ('session_uid', models.CharField(blank=True, db_index=True, help_text='Composite business key: SES-date-YTH-SCH-CH...', max_length=500, null=True)),
                ('session_date', models.DateField(blank=True, null=True)),
                ('youth_uid', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('school_uid', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('child_uids', models.JSONField(blank=True, default=list, help_text='Array of CH-XXXXX UIDs for all children in this session')),
                ('children_count', models.IntegerField(blank=True, null=True)),
                ('group_count_level', models.CharField(blank=True, help_text='e.g. 31-40 (emoji stripped from Airtable value)', max_length=50, null=True)),
                ('group_number_recognition', models.CharField(blank=True, help_text='e.g. Recognises 1-5', max_length=100, null=True)),
                ('duplicate_status', models.CharField(blank=True, max_length=50, null=True)),
                ('overall_session_status', models.CharField(blank=True, max_length=50, null=True)),
                ('capture_delay', models.IntegerField(blank=True, help_text='Days between session date and capture', null=True)),
                ('capture_delay_flag', models.CharField(blank=True, max_length=100, null=True)),
                ('duplicate_fingerprint', models.CharField(blank=True, max_length=500, null=True)),
                ('created_in_airtable', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'numeracy_sessions_2026',
                'indexes': [models.Index(fields=['session_date'], name='numeracy_se_session_093546_idx'), models.Index(fields=['youth_uid'], name='numeracy_se_youth_u_b75856_idx'), models.Index(fields=['school_uid'], name='numeracy_se_school__d10471_idx')],
            },
        ),
    ]
