# Generated by Django 5.1.6 on 2026-03-10 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_numeracysession2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanonicalChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_airtable_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('child_uid', models.CharField(db_index=True, help_text='CH-XXXXX format UID', max_length=50, unique=True)),
                ('mcode', models.IntegerField(db_index=True, help_text='Stable integer child identifier', unique=True)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('surname', models.CharField(blank=True, max_length=200, null=True)),
                ('full_name', models.CharField(blank=True, max_length=400, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('identity_confidence', models.CharField(blank=True, help_text='e.g. Multi-Year Record', max_length=100, null=True)),
                ('years_active', models.JSONField(blank=True, default=list, help_text='List of years the child was active')),
                ('programme', models.JSONField(blank=True, default=list, help_text="e.g. ['Literacy Child']")),
                ('school_2025', models.CharField(blank=True, max_length=200, null=True)),
                ('grade_2025', models.CharField(blank=True, max_length=50, null=True)),
                ('created_in_airtable', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'canonical_children',
                'ordering': ['mcode'],
            },
        ),
    ]
