# Generated by Django 5.1.6 on 2026-03-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_canonical_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_number',
            field=models.IntegerField(blank=True, help_text='Auto-increment number from Airtable', null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='school_uid',
            field=models.CharField(blank=True, db_index=True, help_text='SCH-XXXXX format UID — join key for 2026 session tables', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='school',
            name='suburb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
