# Generated by Django 5.1.6 on 2026-03-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_youth_uid_mentor_hr_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_airtable_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('employee_number', models.IntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('first_names', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('race', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('id_number', models.CharField(blank=True, max_length=50, null=True)),
                ('identification_type', models.CharField(blank=True, max_length=50, null=True)),
                ('drivers_license_code', models.CharField(blank=True, max_length=50, null=True)),
                ('cell_number', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('emergency_cell_number', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_number', models.CharField(blank=True, max_length=50, null=True)),
                ('complex_name', models.CharField(blank=True, max_length=100, null=True)),
                ('street_number', models.CharField(blank=True, max_length=50, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('suburb', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
                'db_table': 'staff',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='cell_number',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='city',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='complex_name',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='drivers_license_code',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='emergency_cell_number',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='employee_number',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='first_names',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='identification_type',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='race',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='source_airtable_id',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='street',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='street_number',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='suburb',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='unit_number',
        ),
    ]
