# Generated by Django 5.1.6 on 2026-03-12 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_revert_mentor_add_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='literacysession2026',
            name='child_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='literacy_sessions_as_child1', to='api.canonicalchild'),
        ),
        migrations.AddField(
            model_name='literacysession2026',
            name='child_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='literacy_sessions_as_child2', to='api.canonicalchild'),
        ),
        migrations.AddField(
            model_name='literacysession2026',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='literacy_sessions_2026', to='api.school'),
        ),
        migrations.AddField(
            model_name='literacysession2026',
            name='youth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='literacy_sessions_2026', to='api.youth'),
        ),
        migrations.AddField(
            model_name='numeracysession2026',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='numeracy_sessions_2026', to='api.school'),
        ),
        migrations.AddField(
            model_name='numeracysession2026',
            name='youth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='numeracy_sessions_2026', to='api.youth'),
        ),
    ]
