# Generated by Django 5.1.6 on 2026-06-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_literacysession2026_child_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZaziOverviewSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('fetched_at', models.DateTimeField(blank=True, help_text='When the payload was last fetched successfully', null=True)),
                ('ok', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zazi Overview Snapshot',
                'verbose_name_plural': 'Zazi Overview Snapshots',
            },
        ),
    ]
