# Generated by Django 5.1.6 on 2026-06-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_zazioverviewsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='zazioverviewsnapshot',
            name='cohort',
            field=models.CharField(default='all', help_text="Zazi programme-overview cohort: 'primary' or 'ecd' (one row each)", max_length=20, unique=True),
        ),
    ]
