# Generated by Django 5.1.6 on 2026-06-09 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_zazioverviewsnapshot_cohort'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('scope_key', models.CharField(blank=True, db_index=True, max_length=120)),
                ('scope_type', models.CharField(choices=[('global', 'Global (all schools)'), ('type', 'By school type'), ('region', 'By region (suburb)'), ('school', 'Single school')], max_length=10)),
                ('scope_school_type', models.CharField(blank=True, choices=[('primary', 'Primary'), ('ecd', 'ECD'), ('secondary', 'Secondary'), ('other', 'Other')], max_length=10, null=True)),
                ('scope_region', models.CharField(blank=True, max_length=100, null=True)),
                ('is_open', models.BooleanField(default=False, help_text="True = explicit 'actually open' override of a broader closure")),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('public_holiday', 'Public holiday')], db_index=True, default='manual', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('scope_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closures', to='api.school')),
            ],
            options={
                'ordering': ['-date', 'scope_key'],
                'indexes': [models.Index(fields=['date', 'scope_type'], name='api_schoolc_date_1446b7_idx')],
                'constraints': [models.UniqueConstraint(fields=('date', 'scope_key'), name='uniq_closure_date_scope')],
            },
        ),
        migrations.CreateModel(
            name='StaffAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youth_uid', models.CharField(blank=True, db_index=True, help_text='YTH-XXXX; stable key, survives youth re-sync', max_length=50)),
                ('date', models.DateField(db_index=True)),
                ('reason', models.CharField(choices=[('vacation', 'Vacation'), ('funeral', 'Funeral'), ('sick', 'Sick'), ('other', 'Other')], default='other', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('youth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absences', to='api.youth')),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('date', 'youth_uid'), name='uniq_absence_date_youth_uid')],
            },
        ),
    ]
