# Generated by Django 5.1.6 on 2026-06-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_schoolclosure_staffabsence'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('value', models.CharField(help_text="Display string, e.g. '19,444' or '53%'", max_length=40)),
                ('numeric_value', models.FloatField(blank=True, null=True)),
                ('numeric_value_secondary', models.FloatField(blank=True, help_text='Second number for baseline/endline pairs (numeric_value=endline, secondary=baseline)', null=True)),
                ('label', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('source_system', models.CharField(max_length=200)),
                ('population', models.CharField(blank=True, default='', max_length=200)),
                ('comparison_type', models.CharField(choices=[('none', 'None'), ('comparison_group', 'Comparison group'), ('control_group', 'Control group'), ('benchmark', 'Benchmark')], default='none', max_length=20)),
                ('as_of', models.DateField()),
                ('methodology_note', models.TextField(blank=True, default='')),
                ('group', models.CharField(blank=True, default='', max_length=60)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['group', 'sort_order'],
            },
        ),
    ]
