# Generated by Django 5.1.6 on 2026-06-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_publishedstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='canonicalchild',
            name='participant_id',
            field=models.CharField(blank=True, db_index=True, help_text="TeamPact participant id (from Airtable 'Teampact Participant ID' lookup) -- join key to Zazi TeampactParticipant.participant_id", max_length=50, null=True),
        ),
    ]
