# Generated by Django 5.1.6 on 2026-06-18 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_canonicalchild_participant_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolProgrammeYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme', models.CharField(choices=[('zazi_izandi', 'Zazi iZandi'), ('masi_literacy', 'Masi Literacy'), ('numeracy', 'Numeracy'), ('thousand_stories', '1000 Stories'), ('edutech', 'EduTech'), ('yebo', 'Yebo'), ('sport_arts', 'Sport & Arts'), ('homework', 'Homework'), ('preschool', 'Preschool')], max_length=30)),
                ('year', models.IntegerField()),
                ('children_count', models.IntegerField(blank=True, null=True)),
                ('count_basis', models.CharField(choices=[('child_level', 'Child-level'), ('whole_school', 'Whole school'), ('percent_of_school', 'Percent of school')], default='child_level', max_length=20)),
                ('count_source', models.CharField(choices=[('computed', 'Computed'), ('manual', 'Manual')], default='manual', max_length=10)),
                ('percent_of_school', models.DecimalField(blank=True, decimal_places=2, help_text='Only when count_basis = percent_of_school (e.g. 1000 Stories in primaries).', max_digits=5, null=True)),
                ('youth_planned', models.IntegerField(blank=True, help_text="Human: management's staffing allocation.", null=True)),
                ('youth_active', models.IntegerField(default=0, help_text='System: active youth on this programme at this school (cron).')),
                ('as_of', models.DateTimeField(blank=True, help_text='Last cron refresh of the system-owned columns.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programme_years', to='api.school')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['school', 'programme'],
                'unique_together': {('school', 'programme', 'year')},
            },
        ),
        migrations.CreateModel(
            name='SchoolYearStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('total_kids_in_school', models.IntegerField(blank=True, help_text='Human: school enrolment.', null=True)),
                ('pct_african', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pct_coloured', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pct_white', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pct_female', models.DecimalField(blank=True, decimal_places=2, help_text="System: % female across this school's deduped children (CanonicalChild.gender).", max_digits=5, null=True)),
                ('demographic_source', models.CharField(blank=True, default='', help_text="Human: e.g. 'school estimate (Astra)'.", max_length=200)),
                ('unique_beneficiaries', models.IntegerField(blank=True, help_text="System: distinct child identities across the school's programmes (section 7).", null=True)),
                ('as_of', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_stats', to='api.school')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'School year stats',
                'ordering': ['school'],
                'unique_together': {('school', 'year')},
            },
        ),
    ]
