# Generated by Django 5.1.6 on 2026-06-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_schoolprogrammeyear_schoolyearstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtablesynclog',
            name='details',
            field=models.JSONField(blank=True, help_text='Structured per-sync report (e.g. the grid health/integrity flags).', null=True, verbose_name='Details'),
        ),
    ]
