# Generated by Django 5.1.6 on 2026-07-02 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_airtablesynclog_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiteracyAssessment2026',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_airtable_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('source_created_time', models.DateTimeField(blank=True, help_text='Airtable record createdTime; recency tiebreak fallback', null=True)),
                ('source_modified_time', models.DateTimeField(blank=True, help_text="Airtable 'Last Modified Time' field if present; preferred recency signal", null=True)),
                ('assessment_uid', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('child_uid', models.CharField(db_index=True, max_length=50)),
                ('year', models.IntegerField(db_index=True)),
                ('term', models.CharField(db_index=True, help_text='Jan / Jun / Nov', max_length=8)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('letter_sounds', models.FloatField(blank=True, null=True)),
                ('story_comprehension', models.FloatField(blank=True, null=True)),
                ('listen_first_sound', models.FloatField(blank=True, null=True)),
                ('listen_words', models.FloatField(blank=True, null=True)),
                ('writing_letters', models.FloatField(blank=True, null=True)),
                ('read_words', models.FloatField(blank=True, null=True)),
                ('read_sentences', models.FloatField(blank=True, null=True)),
                ('read_story', models.FloatField(blank=True, null=True)),
                ('write_cvcs', models.FloatField(blank=True, null=True)),
                ('write_sentences', models.FloatField(blank=True, null=True)),
                ('write_story', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('programme_belonging', models.JSONField(blank=True, default=list)),
                ('duplicate_status', models.CharField(blank=True, max_length=100, null=True)),
                ('capture_status', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='literacy_assessments_2026', to='api.canonicalchild')),
            ],
            options={
                'db_table': 'literacy_assessments_2026',
                'ordering': ['child_uid', 'year', 'term'],
                'indexes': [models.Index(fields=['child_uid', 'term', 'year'], name='literacy_as_child_u_07c908_idx')],
            },
        ),
    ]
