# Generated by Django 5.1.6 on 2026-07-02 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_literacyassessment2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnTheProgramme2026',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_airtable_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('child_uid', models.CharField(db_index=True, max_length=50, unique=True)),
                ('on_the_programme', models.BooleanField(default=True)),
                ('mentor', models.CharField(blank=True, max_length=200, null=True)),
                ('school', models.CharField(blank=True, max_length=200, null=True)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('all_sessions_count', models.IntegerField(blank=True, null=True)),
                ('valid_learning_records_count', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'on_the_programme_2026',
                'ordering': ['child_uid'],
            },
        ),
    ]
