# Generated by Django 5.1.6 on 2026-07-13 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_ontheprogramme2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumeracyOnTheProgramme2026',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_airtable_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('child_uid', models.CharField(db_index=True, max_length=50, unique=True)),
                ('programme_status', models.CharField(blank=True, max_length=100, null=True)),
                ('programme_belonging', models.JSONField(blank=True, default=list)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('school', models.CharField(blank=True, max_length=255, null=True)),
                ('mentor', models.CharField(blank=True, max_length=255, null=True)),
                ('numeracy_coach', models.CharField(blank=True, max_length=255, null=True)),
                ('total_sessions', models.IntegerField(blank=True, null=True)),
                ('session_school_count', models.IntegerField(blank=True, null=True)),
                ('source_session_ids', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='numeracy_roster_2026', to='api.canonicalchild')),
            ],
            options={
                'db_table': 'numeracy_on_the_programme_2026',
                'ordering': ['child_uid'],
            },
        ),
        migrations.CreateModel(
            name='NumeracyAssessment2026',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_airtable_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('source_created_time', models.DateTimeField(blank=True, null=True)),
                ('assessment_uid', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('child_uid', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('year', models.IntegerField(db_index=True)),
                ('term', models.CharField(db_index=True, max_length=20)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('counting_aloud', models.FloatField(blank=True, null=True)),
                ('number_recognition', models.FloatField(blank=True, null=True)),
                ('counting_matching', models.FloatField(blank=True, null=True)),
                ('write_numbers', models.FloatField(blank=True, null=True)),
                ('identification', models.FloatField(blank=True, null=True)),
                ('missing_numbers', models.FloatField(blank=True, null=True)),
                ('sum_10', models.FloatField(blank=True, null=True)),
                ('word_problems', models.FloatField(blank=True, null=True)),
                ('addition_subtraction', models.FloatField(blank=True, null=True)),
                ('total_raw', models.FloatField(blank=True, null=True)),
                ('assessment_percent', models.FloatField(blank=True, null=True)),
                ('programme_belonging', models.JSONField(blank=True, default=list)),
                ('source_child_ids', models.JSONField(blank=True, default=list)),
                ('source_school_ids', models.JSONField(blank=True, default=list)),
                ('source_assessor_ids', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='numeracy_assessments_2026', to='api.canonicalchild')),
            ],
            options={
                'db_table': 'numeracy_assessments_2026',
                'ordering': ['child_uid', 'year', 'term', 'source_airtable_id'],
                'indexes': [models.Index(fields=['child_uid', 'year', 'term'], name='numeracy_as_child_u_a085ce_idx')],
            },
        ),
    ]
