# Generated by Django 5.1.6 on 2026-07-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_ontheprogramme2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclosure',
            name='applies_to_programmes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
