# Generated by Django 5.1.6 on 2026-07-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_youth_budget_calculator'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetscenario',
            name='nys_subsidy_only_count',
            field=models.IntegerField(default=0),
        ),
    ]
