# Generated by Django 5.1.6 on 2026-07-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_budget_scenario_subsidy_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetscenario',
            name='utilisation_pct',
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
