# Generated by Django 5.1.6 on 2026-07-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_budget_scenario_utilisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingpot',
            name='is_ringfenced',
            field=models.BooleanField(default=False),
        ),
    ]
