# Generated by Django 5.1.6 on 2026-09-05 17:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def copy_read_grants(apps, schema_editor, *, reverse=False):
    alias = schema_editor.connection.alias
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Permission = apps.get_model('auth', 'Permission')
    old_ct, _ = ContentType.objects.using(alias).get_or_create(app_label='api', model='financesnapshot')
    new_ct, _ = ContentType.objects.using(alias).get_or_create(app_label='api', model='financerun')
    old, _ = Permission.objects.using(alias).get_or_create(content_type=old_ct, codename='read_finance', defaults={'name': 'Can read the finance dashboard'})
    new, _ = Permission.objects.using(alias).get_or_create(content_type=new_ct, codename='read_finance', defaults={'name': 'Can read the finance dashboard'})
    source, target = (new, old) if reverse else (old, new)
    for model_name, field in (('User', 'user'), ('Group', 'group')):
        model = apps.get_model('auth', model_name)
        relation = model.user_permissions if model_name == 'User' else model.permissions
        through = relation.through
        ids = through.objects.using(alias).filter(permission_id=source.pk).values_list(field + '_id', flat=True)
        through.objects.using(alias).bulk_create([
            through(**{field + '_id': pk, 'permission_id': target.pk}) for pk in ids
        ], ignore_conflicts=True)
    if reverse:
        Permission.objects.using(alias).filter(content_type=new_ct, codename__in=['read_finance', 'publish_finance']).delete()
    else:
        Permission.objects.using(alias).get_or_create(content_type=new_ct, codename='publish_finance', defaults={'name': 'Can publish finance runs'})


def reverse_read_grants(apps, schema_editor):
    copy_read_grants(apps, schema_editor, reverse=True)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_finance_read_capability'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('funders', 'Funders')], default='funders', max_length=24)),
                ('accounting_year', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('candidate', 'Candidate'), ('approved', 'Approved'), ('superseded', 'Superseded'), ('failed', 'Failed')], max_length=16)),
                ('source_name', models.CharField(max_length=255)),
                ('source_date', models.DateField()),
                ('source_sha256', models.CharField(db_index=True, max_length=64)),
                ('source_size_bytes', models.PositiveBigIntegerField()),
                ('schema_version', models.CharField(max_length=16)),
                ('producer_version', models.CharField(max_length=32, null=True)),
                ('payload_sha256', models.CharField(max_length=64, null=True)),
                ('facts_sha256', models.CharField(max_length=64, null=True)),
                ('manifest', models.JSONField(default=dict)),
                ('payload', models.JSONField(null=True)),
                ('failure', models.JSONField(null=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('approved_at', models.DateTimeField(null=True)),
                ('approval_overrode_rollback', models.BooleanField(default=False)),
                ('approval_acknowledged_findings', models.BooleanField(default=False)),
                ('approval_note', models.TextField(blank=True, default='')),
                ('demoted_at', models.DateTimeField(null=True)),
                ('demotion_note', models.TextField(blank=True, default='')),
                ('parse_duration_ms', models.PositiveBigIntegerField(default=0)),
                ('total_duration_ms', models.PositiveBigIntegerField(default=0)),
                ('peak_memory_bytes', models.PositiveBigIntegerField(default=0)),
                ('fact_row_count', models.PositiveIntegerField(default=0)),
                ('allocation_count', models.PositiveIntegerField(default=0)),
                ('finding_count', models.PositiveIntegerField(default=0)),
                ('in_scope_error_count', models.PositiveIntegerField(default=0)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_finance_runs', to=settings.AUTH_USER_MODEL)),
                ('demoted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demoted_finance_runs', to=settings.AUTH_USER_MODEL)),
                ('previous_approved', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successors', to='api.financerun')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_finance_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('read_finance', 'Can read the finance dashboard'), ('publish_finance', 'Can publish finance runs')],
            },
        ),
        migrations.CreateModel(
            name='LedgerRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_key', models.TextField()),
                ('sheet_row', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('year', models.IntegerField()),
                ('description', models.TextField()),
                ('paid_by', models.TextField(null=True)),
                ('category_1', models.TextField(null=True)),
                ('category_2', models.TextField(null=True)),
                ('category_3', models.TextField(null=True)),
                ('bc', models.TextField(null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_rows', to='api.financerun')),
            ],
        ),
        migrations.CreateModel(
            name='LedgerAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField()),
                ('amount_column_letter', models.CharField(max_length=3)),
                ('key_column_letter', models.CharField(max_length=3, null=True)),
                ('key_value', models.TextField(null=True)),
                ('contract_code', models.TextField(db_index=True, null=True)),
                ('budget_line_id', models.TextField(null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('ledger_row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='api.ledgerrow')),
            ],
        ),
        migrations.AddIndex(
            model_name='financerun',
            index=models.Index(fields=['kind', 'accounting_year', 'status', '-uploaded_at'], name='finance_run_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='financerun',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'approved')), fields=('kind', 'accounting_year'), name='finance_one_approved'),
        ),
        migrations.AddConstraint(
            model_name='financerun',
            constraint=models.UniqueConstraint(fields=('kind', 'accounting_year', 'source_sha256', 'producer_version'), name='finance_upload_identity'),
        ),
        migrations.AddConstraint(
            model_name='financerun',
            constraint=models.CheckConstraint(condition=models.Q(('accounting_year__gte', 1), ('kind', 'funders'), ('status__in', ['candidate', 'approved', 'superseded', 'failed'])), name='finance_closed_state'),
        ),
        migrations.AddConstraint(
            model_name='financerun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('facts_sha256__isnull', False), ('failure__isnull', True), ('payload__isnull', False), ('payload_sha256__isnull', False), ('producer_version__isnull', False), ('schema_version', '2.0.0'), ('status__in', ['candidate', 'approved', 'superseded'])), models.Q(('allocation_count', 0), ('fact_row_count', 0), ('facts_sha256__isnull', True), ('failure__isnull', True), ('payload__isnull', False), ('payload_sha256__isnull', False), ('producer_version__isnull', True), ('schema_version', '1.0.0'), ('status__in', ['approved', 'superseded'])), models.Q(('allocation_count', 0), ('fact_row_count', 0), ('facts_sha256__isnull', True), ('failure__isnull', False), ('payload__isnull', True), ('payload_sha256__isnull', True), ('producer_version__isnull', False), ('schema_version', '2.0.0'), ('status', 'failed')), _connector='OR'), name='finance_version_payload'),
        ),
        migrations.AddConstraint(
            model_name='financerun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('approved_at__isnull', False), ('approved_by__isnull', False), ('status__in', ['approved', 'superseded'])), models.Q(('approved_at__isnull', True), ('approved_by__isnull', True), ('previous_approved__isnull', True), ('status__in', ['candidate', 'failed'])), _connector='OR'), name='finance_approval_audit'),
        ),
        migrations.AddConstraint(
            model_name='financerun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('demoted_at__isnull', True), ('demoted_by__isnull', True), ('demotion_note', '')), models.Q(('demoted_at__isnull', False), ('demoted_by__isnull', False), models.Q(('demotion_note', ''), _negated=True)), _connector='OR'), name='finance_demotion_audit'),
        ),
        migrations.AddIndex(
            model_name='ledgerrow',
            index=models.Index(fields=['run', 'date'], name='finance_row_date_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerrow',
            index=models.Index(fields=['run', 'year'], name='finance_row_year_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerrow',
            index=models.Index(fields=['run', 'bc'], name='finance_row_bc_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerrow',
            index=models.Index(fields=['run', 'category_2'], name='finance_row_category_2_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgerrow',
            constraint=models.UniqueConstraint(fields=('run', 'row_key'), name='finance_row_identity'),
        ),
        migrations.AddIndex(
            model_name='ledgerallocation',
            index=models.Index(fields=['ledger_row', 'ordinal'], name='finance_allocation_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgerallocation',
            constraint=models.UniqueConstraint(fields=('ledger_row', 'amount_column_letter'), name='finance_allocation_stream'),
        ),
        migrations.AddConstraint(
            model_name='ledgerallocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('amount', 0), _negated=True), ('ordinal__gte', 1)), name='finance_allocation_nonzero'),
        ),
        migrations.AddConstraint(
            model_name='ledgerallocation',
            constraint=models.CheckConstraint(condition=models.Q(('budget_line_id__isnull', True), ('contract_code__isnull', False), _connector='OR'), name='finance_line_has_owner'),
        ),
        migrations.RunPython(copy_read_grants, reverse_read_grants),
    ]
