# Generated by Django 5.1.6 on 2026-09-07 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_finance_runs_foundation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='financerun',
            name='finance_upload_identity',
        ),
        migrations.RemoveConstraint(
            model_name='financerun',
            name='finance_closed_state',
        ),
        migrations.RemoveConstraint(
            model_name='financerun',
            name='finance_version_payload',
        ),
        migrations.AddField(
            model_name='financerun',
            name='dependency_run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dependent_runs', to='api.financerun'),
        ),
        migrations.AlterField(
            model_name='financerun',
            name='kind',
            field=models.CharField(choices=[('funders', 'Funders'), ('budgets', 'Budgets')], default='funders', max_length=24),
        ),
        migrations.AddConstraint(
            model_name='financerun',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'funders')), fields=('kind', 'accounting_year', 'source_sha256', 'producer_version'), name='finance_upload_identity'),
        ),
        migrations.AddConstraint(
            model_name='financerun',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'budgets')), fields=('kind', 'accounting_year', 'source_sha256', 'producer_version', 'dependency_run'), name='finance_budget_upload_identity'),
        ),
        migrations.AddConstraint(
            model_name='financerun',
            constraint=models.CheckConstraint(condition=models.Q(('accounting_year__gte', 1), ('kind__in', ['funders', 'budgets']), ('status__in', ['candidate', 'approved', 'superseded', 'failed'])), name='finance_closed_state'),
        ),
        migrations.AddConstraint(
            model_name='financerun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('dependency_run__isnull', True), ('kind', 'funders'), models.Q(models.Q(('facts_sha256__isnull', False), ('failure__isnull', True), ('payload__isnull', False), ('payload_sha256__isnull', False), ('producer_version__isnull', False), ('schema_version', '2.0.0'), ('status__in', ['candidate', 'approved', 'superseded'])), models.Q(('allocation_count', 0), ('fact_row_count', 0), ('facts_sha256__isnull', True), ('failure__isnull', True), ('payload__isnull', False), ('payload_sha256__isnull', False), ('producer_version__isnull', True), ('schema_version', '1.0.0'), ('status__in', ['approved', 'superseded'])), models.Q(('allocation_count', 0), ('fact_row_count', 0), ('facts_sha256__isnull', True), ('failure__isnull', False), ('payload__isnull', True), ('payload_sha256__isnull', True), ('producer_version__isnull', False), ('schema_version', '2.0.0'), ('status', 'failed')), _connector='OR')), models.Q(('allocation_count', 0), ('dependency_run__isnull', False), ('fact_row_count', 0), ('facts_sha256__isnull', True), ('kind', 'budgets'), ('producer_version__isnull', False), ('schema_version', '1.0.0'), models.Q(models.Q(('failure__isnull', True), ('payload__isnull', False), ('payload_sha256__isnull', False), ('status__in', ['candidate', 'approved', 'superseded'])), models.Q(('failure__isnull', False), ('payload__isnull', True), ('payload_sha256__isnull', True), ('status', 'failed')), _connector='OR')), _connector='OR'), name='finance_version_payload'),
        ),
    ]
