from django.core.management.base import BaseCommand

from api.models import PublishedStat


P = "PROVISIONAL - verify before launch. "

SEEDS = [
    dict(key="hero_children", value="19,444", numeric_value=19444, label="children on programme",
         source_system="Masi Data Site home.py", population="Children on programme, 2026",
         as_of="2026-06-12", methodology_note=P + "Reconcile vs 18,276 (site) / 25,000+ (ZZ).",
         group="hero_kpis", sort_order=1),
    dict(key="hero_schools", value="231", numeric_value=231, label="schools & ECD centres",
         source_system="Masi Data Site home.py", population="Active sites, 2026",
         as_of="2026-06-12", methodology_note=P + "Reconcile vs 154 / 250+.",
         group="hero_kpis", sort_order=2),
    dict(key="hero_youth", value="515", numeric_value=515, label="local youth employed",
         source_system="Masi Data Site home.py", population="Youth employed, 2026",
         as_of="2026-06-12", methodology_note=P + "Decide active vs annual vs cumulative.",
         group="hero_kpis", sort_order=3),
    dict(key="hero_records", value="1.1M", numeric_value=1100000, label="assessment & session records",
         source_system="ZZ DATA_SOURCES_DOCUMENTATION.md", population="All-time records",
         as_of="2026-06-12", methodology_note=P + "Compute real count.",
         group="hero_kpis", sort_order=4),
    dict(key="arg_pirls", value="81%", numeric_value=81,
         label="of South African 10-year-olds cannot read for meaning",
         source_system="PIRLS 2021", population="South African Grade 4 learners",
         as_of="2026-06-12", methodology_note="Published international study.",
         group="argument", sort_order=1),
    dict(key="arg_letter_sounds", value="73%", numeric_value=73,
         label="never learn their letter sounds by the end of Grade 1",
         source_system="Wordworks / Eastern Cape benchmark research",
         population="Eastern Cape Grade 1 learners", comparison_type="benchmark",
         as_of="2026-06-12", methodology_note=P + "Confirm exact phrasing vs 27%-reach-benchmark source.",
         group="argument", sort_order=2),
    dict(key="arg_correlation", value="0.93", numeric_value=0.93,
         label="correlation between our two independent assessment methods",
         source_system="ZZ Research & Benchmarks (Spearman)", population="Programme learners",
         as_of="2026-06-12", methodology_note="Letters Known vs EGRA improvement, rho=0.933.",
         group="argument", sort_order=3),
    dict(key="class_size", value="42", numeric_value=42, label="average Eastern Cape Grade 1 class size",
         source_system="DBE class size data", as_of="2026-06-12",
         methodology_note=P + "Confirm average class size figure.", group="classroom", sort_order=1),
    dict(key="cine_jan", value="13%", numeric_value=13, label="at benchmark, January baseline",
         source_system="Masi Data Site zz_2025_midline.py", population="Grade 1 programme learners, 2025",
         comparison_type="benchmark", as_of="2026-06-12", methodology_note="2025 baseline.",
         group="classroom", sort_order=2),
    dict(key="cine_jun", value="53%", numeric_value=53, label="at benchmark, June midline",
         source_system="Masi Data Site zz_2025_midline.py", population="Grade 1 programme learners, 2025",
         comparison_type="benchmark", as_of="2026-06-12", methodology_note="2025 midline.",
         group="classroom", sort_order=3),
    dict(key="cine_comparison", value="27%", numeric_value=27,
         label="at benchmark, comparison schools full year",
         source_system="Masi uts_me_benchmarks.py", population="isiXhosa comparison-school Grade 1s",
         comparison_type="comparison_group", as_of="2026-06-12",
         methodology_note="Use 'comparison group' wording.", group="classroom", sort_order=4),
    dict(key="cine_endline_2023", value="74%", numeric_value=74,
         label="at benchmark, 2023 cohort endline",
         source_system="ZZ 2023 Results", population="Grade 1 programme learners, 2023",
         comparison_type="benchmark", as_of="2026-06-12", methodology_note="2023 pilot endline.",
         group="classroom", sort_order=5),
    dict(key="ecd_masi_lcpm", value="14.9", numeric_value=14.9,
         label="Masi ECD letters correct per minute (ages 4-5)",
         source_system="2026 live assessment data (ECD midline)", population="Masi ECD learners, 2026",
         as_of="2026-06-12", methodology_note="Confirmed by Jim 2026-06-12.",
         group="ecd", sort_order=1),
    dict(key="ecd_g1_lcpm", value="15.4", numeric_value=15.4,
         label="Grade 1 comparison letters correct per minute (ages 6-7)",
         source_system="2026 live assessment data (Grade 1 comparison)",
         population="Grade 1 comparison-group learners, 2026", comparison_type="comparison_group",
         as_of="2026-06-12", methodology_note="Confirmed by Jim 2026-06-12.",
         group="ecd", sort_order=2),
    dict(key="num_avg_gain", value="+21", numeric_value=21, label="average score gain out of 90",
         source_system="Masi numeracy_assessments_25.py", population="Matched baseline-endline learners, 2025",
         as_of="2026-06-12", methodology_note=P + "Confirm exact average gain.",
         group="numeracy", sort_order=1),
    dict(key="num_counting", value="8.8", numeric_value=8.8, numeric_value_secondary=6.1,
         label="Counting aloud", source_system="Masi numeracy_assessments_25.py",
         as_of="2026-06-12", methodology_note=P, group="numeracy_components", sort_order=1),
    dict(key="num_recognition", value="7.4", numeric_value=7.4, numeric_value_secondary=4.8,
         label="Number recognition", source_system="Masi numeracy_assessments_25.py",
         as_of="2026-06-12", methodology_note=P, group="numeracy_components", sort_order=2),
    dict(key="num_sums", value="5.8", numeric_value=5.8, numeric_value_secondary=3.0,
         label="Sums to 10", source_system="Masi numeracy_assessments_25.py",
         as_of="2026-06-12", methodology_note=P, group="numeracy_components", sort_order=3),
    dict(key="num_th_count20", value="81%", numeric_value=81, label="can count to 20+",
         source_system="Masi numeracy_assessments_25.py", as_of="2026-06-12",
         methodology_note=P, group="numeracy_thresholds", sort_order=1),
    dict(key="num_th_id100", value="64%", numeric_value=64, label="identify numbers to 100",
         source_system="Masi numeracy_assessments_25.py", as_of="2026-06-12",
         methodology_note=P, group="numeracy_thresholds", sort_order=2),
    dict(key="num_th_write10", value="72%", numeric_value=72, label="write numbers 1-10",
         source_system="Masi numeracy_assessments_25.py", as_of="2026-06-12",
         methodology_note=P, group="numeracy_thresholds", sort_order=3),
    dict(key="grads_count", value="454", numeric_value=454, label="university graduates",
         source_system="Website home page", as_of="2026-06-12",
         methodology_note=P + "Confirm current count.", group="graduates", sort_order=1),
    dict(key="grads_women", value="95%", numeric_value=95, label="of staff are women",
         source_system="Website about page", as_of="2026-06-12",
         methodology_note=P + "Verify current figure.", group="graduates", sort_order=2),
    dict(key="more_zero_letters", value="51% -> 12%", numeric_value=12, numeric_value_secondary=51,
         label="children with zero letter knowledge, January to November",
         source_system="ZZ letter_knowledge_2024.py", as_of="2026-06-12",
         methodology_note=P + "Confirm endline zero-letter percentage.", group="more_results", sort_order=1),
    dict(key="more_growth", value="3x", numeric_value=3,
         label="faster letter-fluency growth than comparison learners",
         source_system="ZZ midline_primary_2026.py", comparison_type="comparison_group",
         as_of="2026-06-12", methodology_note=P + "Confirm multiple.",
         group="more_results", sort_order=2),
    dict(key="more_stories", value="120k+", numeric_value=120000,
         label="stories read aloud to young children (1000 Stories)",
         source_system="Masi uts_1000_stories.py", as_of="2026-06-12",
         methodology_note=P + "Pull real total.", group="more_results", sort_order=3),
    dict(key="more_correlation", value="0.93", numeric_value=0.93,
         label="correlation between our two independent assessment methods",
         source_system="ZZ Research & Benchmarks (Spearman)", as_of="2026-06-12",
         methodology_note="rho=0.933.", group="more_results", sort_order=4),
]


class Command(BaseCommand):
    help = "Seed the published-stats store with the spec's launch set (idempotent upsert by key)."

    def handle(self, *args, **options):
        created = updated = 0
        for row in SEEDS:
            row.setdefault("is_published", True)
            _, was_created = PublishedStat.objects.update_or_create(key=row["key"], defaults=row)
            created += was_created
            updated += not was_created

        self.stdout.write(self.style.SUCCESS(f"Seeded published stats: {created} created, {updated} updated"))
