# Generated by Django 5.1.6 on 2026-07-07 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('theme', models.CharField(blank=True, default='', max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fundraising_campaign',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('individual', 'Individual'), ('foundation', 'Foundation'), ('corporate', 'Corporate'), ('government', 'Government')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('role_title', models.CharField(blank=True, default='', max_length=120)),
                ('tier', models.CharField(blank=True, choices=[('1_personal', 'Tier 1 - Personal'), ('2_warm', 'Tier 2 - Warm'), ('3_list', 'Tier 3 - List')], default='', max_length=12)),
                ('segment', models.CharField(blank=True, choices=[('us', 'US donors'), ('rsa_eu', 'RSA & EU donors'), ('foundations', 'Foundations')], default='', max_length=20)),
                ('primary_email', models.EmailField(blank=True, default='', max_length=254)),
                ('emails', models.JSONField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('newsletter_consent', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('private_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='fundraising.contact')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='fundraising.contact')),
            ],
            options={
                'db_table': 'fundraising_contact',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContactMergeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loser_snapshot', models.JSONField()),
                ('reason', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merges_lost', to='fundraising.contact')),
                ('merged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merges_won', to='fundraising.contact')),
            ],
            options={
                'db_table': 'fundraising_contact_merge_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('ZAR', 'South African Rand'), ('EUR', 'Euro'), ('GBP', 'British Pound')], max_length=3)),
                ('receiving_entity', models.CharField(blank=True, choices=[('us', 'US 501(c)(3)'), ('sa', 'South Africa')], default='', max_length=4)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('agreement_reference', models.CharField(blank=True, default='', max_length=120)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grants', to='fundraising.contact')),
            ],
            options={
                'db_table': 'fundraising_grant',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('annual_grant', 'Annual grant contract'), ('monthly_donor', 'Monthly donor')], max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, choices=[('USD', 'US Dollar'), ('ZAR', 'South African Rand'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='', max_length=3)),
                ('cadence', models.CharField(choices=[('annual', 'Annual'), ('monthly', 'Monthly')], max_length=10)),
                ('next_expected_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expectations', to='fundraising.contact')),
                ('grant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expectations', to='fundraising.grant')),
            ],
            options={
                'db_table': 'fundraising_expectation',
                'ordering': ['next_expected_date'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiving_entity', models.CharField(choices=[('us', 'US 501(c)(3)'), ('sa', 'South Africa')], max_length=4)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('ZAR', 'South African Rand'), ('EUR', 'Euro'), ('GBP', 'British Pound')], max_length=3)),
                ('date', models.DateField()),
                ('method', models.CharField(blank=True, default='', max_length=40)),
                ('source_reference', models.CharField(blank=True, default='', max_length=120)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='fundraising.contact')),
                ('grant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='fundraising.grant')),
            ],
            options={
                'db_table': 'fundraising_donation',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('stage', models.CharField(choices=[('identified', 'Identified'), ('cultivating', 'Cultivating'), ('applied', 'Applied'), ('won', 'Won'), ('declined', 'Declined')], default='identified', max_length=20)),
                ('amount_requested', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, choices=[('USD', 'US Dollar'), ('ZAR', 'South African Rand'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='', max_length=3)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('opened_at', models.DateField(blank=True, null=True)),
                ('closed_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='fundraising.contact')),
                ('renews_grant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='fundraising.grant')),
            ],
            options={
                'db_table': 'fundraising_opportunity',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='grant',
            name='opportunity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grant', to='fundraising.opportunity'),
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('newsletter_broadcast', 'Newsletter broadcast'), ('personal_send', 'Personal send'), ('grant_answer', 'Grant answer'), ('grant_application', 'Grant application'), ('report_narrative', 'Report narrative'), ('interaction_capture', 'Interaction capture'), ('other', 'Other')], max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('sent', 'Sent'), ('discarded', 'Discarded')], default='draft', max_length=12)),
                ('created_by_agent', models.CharField(blank=True, default='', max_length=60)),
                ('subject', models.CharField(blank=True, default='', max_length=300)),
                ('draft_body', models.TextField()),
                ('final_body', models.TextField(blank=True, default='')),
                ('edit_classification', models.JSONField(blank=True, null=True)),
                ('external_ref', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='fundraising.campaign')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='fundraising.contact')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='fundraising.opportunity')),
            ],
            options={
                'db_table': 'fundraising_draft',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email_sent', 'Email sent'), ('email_received', 'Email received'), ('newsletter', 'Newsletter'), ('meeting', 'Meeting'), ('call', 'Call'), ('note', 'Note')], max_length=20)),
                ('direction', models.CharField(blank=True, choices=[('outbound', 'Outbound'), ('inbound', 'Inbound'), ('internal', 'Internal')], default='', max_length=10)),
                ('occurred_at', models.DateTimeField()),
                ('summary', models.CharField(blank=True, default='', max_length=300)),
                ('body', models.TextField(blank=True, default='')),
                ('external_id', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='fundraising.campaign')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='fundraising.contact')),
                ('source_draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='fundraising.draft')),
            ],
            options={
                'db_table': 'fundraising_interaction',
                'ordering': ['-occurred_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('external_id',), name='interaction_external_id_unique')],
            },
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('application_step', 'Application step'), ('report', 'Report')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('submitted', 'Submitted'), ('done', 'Done'), ('waived', 'Waived')], default='open', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='fundraising.grant')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='fundraising.opportunity')),
            ],
            options={
                'db_table': 'fundraising_deliverable',
                'ordering': ['due_date'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('opportunity__isnull', False), ('grant__isnull', True)), models.Q(('opportunity__isnull', True), ('grant__isnull', False)), _connector='OR'), name='deliverable_exactly_one_parent')],
            },
        ),
    ]
