# Generated by Django 5.1.6 on 2026-07-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_airtable_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('feature_name', models.CharField(blank=True, default='', max_length=200)),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('headline', models.TextField(blank=True, default='')),
                ('narrative', models.TextField(blank=True, default='')),
                ('quote', models.TextField(blank=True, default='')),
                ('stats_text', models.TextField(blank=True, default='')),
                ('category', models.JSONField(blank=True, null=True)),
                ('school', models.JSONField(blank=True, null=True)),
                ('date_published', models.DateField(blank=True, null=True)),
                ('photo_urls', models.JSONField(blank=True, null=True)),
                ('has_consent', models.BooleanField(default=False)),
                ('drive_link', models.CharField(blank=True, default='', max_length=500)),
                ('social_published', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fundraising_content_story',
                'ordering': ['-date_published'],
            },
        ),
    ]
