# Generated by Django 5.1.6 on 2026-07-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0002_contentstory'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentstory',
            name='hero_image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
