# Generated by Django 5.1.6 on 2026-07-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0003_contentstory_hero_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='source_meta',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
